### ISSUE TITLE
point cloud drift

### ISSUE THREAD

**Issue by FENGZHANG123** [LiHeUA/IGICP#1]
![image](https://github.com/LiHeUA/IGICP/assets/22960201/e28c1794-17ce-4865-8927-42ee5b67ff0hia)
hi, use your data and code, the registration result is bad, had you met this problem?

**Comment by FENGZHANG123** [comment]
![Snipaste_2024-03-14_17-35-58](https://github.com/LiHeUA/IGICP/assets/22960201/51bfb556-89c9-4093-976a-56c598bc4e21)

**Comment by FENGZHANG123** [comment]
problem solved

**Comment by LiHeUA** [comment]
Good luck and happy hacking. You can contact me via hel@sustech.edu.cn or Mr. Wen Li via 2112101119@mail2.gdut.edu.cn. Github messages are not frequently checked.

**Comment by FENGZHANG123** [comment]
sure, thanks

**Comment by FENGZHANG123** [comment]
solved
